=== rickKase/JavaMapper/data/schema/automata.dtd
<!ELEMENT automata (tokenType, numberOfStates, finalState*, defaultMap*,
		transition*)>
<!ELEMENT tokenType (#PCDATA)>
<!ELEMENT numberOfStates (#PCDATA)>
<!ELEMENT finalState (#PCDATA)>
<!ELEMENT defaultMap (startState, endState)>
<!ELEMENT startState (#PCDATA)>
<!ELEMENT endState (#PCDATA)>
<!ELEMENT transition (startState, endState, trigger*)>
<!ELEMENT trigger (#PCDATA)>

<!ELEMENT compoundAutomata (tokenType, numberOfStates, finalState*,
		defaultMap*, transition*, subAutomata*)>
<!ELEMENT subAutomata (startState, automata)>

=== rickKase/JavaMapper/data/recognizers/string.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE compoundAutomata SYSTEM "..\schema\automata.dtd">
<compoundAutomata>
	<tokenType>STRING_LITERAL</tokenType>
	<numberOfStates>3</numberOfStates>
	<finalState>2</finalState>
	<defaultMap>
		<startState>1</startState>
		<endState>1</endState>
	</defaultMap>
	<transition>
		<startState>0</startState>
		<endState>1</endState>
		<trigger>"</trigger>
	</transition>
	<transition>
		<startState>1</startState>
		<endState>2</endState>
		<trigger>"</trigger>
	</transition>

	<subAutomata>
		<startState>1</startState>
		<automata>
			<tokenType>JAVA_SPECIAL_CHARACTER</tokenType>
			<numberOfStates>3</numberOfStates>
			<finalState>2</finalState>
			<transition>
				<startState>0</startState>
				<endState>1</endState>
				<trigger>\</trigger>
			</transition>
			<transition>
				<startState>1</startState>
				<endState>2</endState>
				<trigger>'</trigger>
				<trigger>"</trigger>
				<trigger>\</trigger>
				<trigger>n</trigger>
				<trigger>b</trigger>
				<trigger>r</trigger>
				<trigger>f</trigger>
				<trigger>t</trigger>
			</transition>
		</automata>
	</subAutomata>

	<subAutomata>
		<startState>1</startState>
		<automata>
			<tokenType>UNICODE_CHARACTER</tokenType>
			<numberOfStates>7</numberOfStates>
			<finalState>6</finalState>
			<transition>
				<startState>0</startState>
				<endState>1</endState>
				<trigger>\</trigger>
			</transition>
			<transition>
				<startState>1</startState>
				<endState>2</endState>
				<trigger>u</trigger>
			</transition>
			<transition>
				<startState>2</startState>
				<endState>3</endState>
				<trigger>0</trigger>
				<trigger>1</trigger>
				<trigger>2</trigger>
				<trigger>3</trigger>
				<trigger>4</trigger>
				<trigger>5</trigger>
				<trigger>6</trigger>
				<trigger>7</trigger>
				<trigger>8</trigger>
				<trigger>9</trigger>
				<trigger>a</trigger>
				<trigger>b</trigger>
				<trigger>c</trigger>
				<trigger>d</trigger>
				<trigger>e</trigger>
				<trigger>f</trigger>
				<trigger>A</trigger>
				<trigger>B</trigger>
				<trigger>C</trigger>
				<trigger>D</trigger>
				<trigger>E</trigger>
				<trigger>F</trigger>
			</transition>
			<transition>
				<startState>3</startState>
				<endState>4</endState>
				<trigger>0</trigger>
				<trigger>1</trigger>
				<trigger>2</trigger>
				<trigger>3</trigger>
				<trigger>4</trigger>
				<trigger>5</trigger>
				<trigger>6</trigger>
				<trigger>7</trigger>
				<trigger>8</trigger>
				<trigger>9</trigger>
				<trigger>a</trigger>
				<trigger>b</trigger>
				<trigger>c</trigger>
				<trigger>d</trigger>
				<trigger>e</trigger>
				<trigger>f</trigger>
				<trigger>A</trigger>
				<trigger>B</trigger>
				<trigger>C</trigger>
				<trigger>D</trigger>
				<trigger>E</trigger>
				<trigger>F</trigger>
			</transition>
			<transition>
				<startState>4</startState>
				<endState>5</endState>
				<trigger>0</trigger>
				<trigger>1</trigger>
				<trigger>2</trigger>
				<trigger>3</trigger>
				<trigger>4</trigger>
				<trigger>5</trigger>
				<trigger>6</trigger>
				<trigger>7</trigger>
				<trigger>8</trigger>
				<trigger>9</trigger>
				<trigger>a</trigger>
				<trigger>b</trigger>
				<trigger>c</trigger>
				<trigger>d</trigger>
				<trigger>e</trigger>
				<trigger>f</trigger>
				<trigger>A</trigger>
				<trigger>B</trigger>
				<trigger>C</trigger>
				<trigger>D</trigger>
				<trigger>E</trigger>
				<trigger>F</trigger>
			</transition>
			<transition>
				<startState>5</startState>
				<endState>6</endState>
				<trigger>0</trigger>
				<trigger>1</trigger>
				<trigger>2</trigger>
				<trigger>3</trigger>
				<trigger>4</trigger>
				<trigger>5</trigger>
				<trigger>6</trigger>
				<trigger>7</trigger>
				<trigger>8</trigger>
				<trigger>9</trigger>
				<trigger>a</trigger>
				<trigger>b</trigger>
				<trigger>c</trigger>
				<trigger>d</trigger>
				<trigger>e</trigger>
				<trigger>f</trigger>
				<trigger>A</trigger>
				<trigger>B</trigger>
				<trigger>C</trigger>
				<trigger>D</trigger>
				<trigger>E</trigger>
				<trigger>F</trigger>
			</transition>
		</automata>
	</subAutomata>
</compoundAutomata>
