=== rickKase/JavaMapper/data/schema/FiniteAutomata.dtd
<!ELEMENT finiteAutomata (tokenType, numberOfStates, finalState*, defaultMap*, transition*)>
<!ELEMENT tokenType (#PCDATA)>
<!ELEMENT numberOfStates (#PCDATA)>
<!ELEMENT finalState (#PCDATA)>
<!ELEMENT defaultMap (startState, endState)>
<!ELEMENT startState (#PCDATA)>
<!ELEMENT endState (#PCDATA)>
<!ELEMENT transition (startState, endState, trigger*)>
<!ELEMENT trigger (#PCDATA)>

=== rickKase/JavaMapper/data/recognizers/multiline-comment.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE finiteAutomata SYSTEM "..\schema\FiniteAutomata.dtd">
<finiteAutomata>
	<tokenType>MULTILINE_COMMENT</tokenType>
	<numberOfStates>5</numberOfStates>
	<finalState>4</finalState>
	<defaultMap>
		<startState>2</startState>
		<endState>2</endState>
	</defaultMap>
	<defaultMap>
		<startState>3</startState>
		<endState>2</endState>
	</defaultMap>
	<transition>
		<startState>0</startState>
		<endState>1</endState>
		<trigger>/</trigger>
	</transition>
	<transition>
		<startState>1</startState>
		<endState>2</endState>
		<trigger>*</trigger>
	</transition>
	<transition>
		<startState>2</startState>
		<endState>3</endState>
		<trigger>*</trigger>
	</transition>
	<transition>
		<startState>3</startState>
		<endState>3</endState>
		<trigger>*</trigger>
	</transition>
	<transition>
		<startState>3</startState>
		<endState>4</endState>
		<trigger>/</trigger>
	</transition>
</finiteAutomata>
